export { default as Page } from "./page";
export { default as Skill } from "./skill";
export { default as Skills } from "./skills";
export { default as DevInfo } from "./devInfo";
export { default as DevWorkCount } from "./devWorkCount";
export { default as DevXpTimeline } from "./devXpTimeline";
export { default as ShowProjects } from "./showProjects";
export { default as CommentsSlider } from "./commentsSlider";
export { default as ContactForm } from "./contactForm";